name: Run Python Script
on:
  schedule:
    - cron: "0 9 * * *" # Runs daily, at 9am
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create .env file
        run: |
          echo "ATLAS_URI=${{ secrets.ATLAS_URI }}" > .env

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Upload detailed log file
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: app-log
          path: app.log
