name: Run Python Script
on:
  schedule:
    - cron: "15 * * * *" # Runs every hour, adjust to your needs
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
        run: python main.py

      - name: Upload detailed log file
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: app-log
          path: app.log
